image: docker:20.10.16

services:
  - docker:20.10.16-dind

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ''
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  script:
    - docker login  -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $TAG_COMMIT .
    - docker push $TAG_COMMIT
  only:
    - main

deploy:
  image: ubuntu:latest
  stage: deploy
  tags:
    - deployment
  script:
    - echo "get variables $RSA_KEY $SERVER_IP"
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - eval $(ssh-agent -s)
    - echo "$RSA_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $SERVER_USER@$SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh $SERVER_USER@$SERVER_IP "docker container rm -v -f dropdex-web || true"
    - ssh $SERVER_USER@$SERVER_IP "docker system prune -f"
    - ssh $SERVER_USER@$SERVER_IP "docker run -d -p 3000:3000 --name dropdex-web $TAG_COMMIT"

  only:
    - main
